# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9bbe89c776b2b40aa9a5b0744b95190e316b57cd1ccf12831a07fe2c88eb34d649679e290aec2183e55f246e1d2e7be90fa27f9268d38613faa50e5d5cea886

test:
  secret_key_base: a77dc3615360e4d5d590a3ad8e20d0875247d99aba5342c7a63b5ab1ba5f1b7b6c5206159ea1eec141062de529787143d31d6ce3dfb466bcbef33c725b4c9162

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
